apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  selector:
    matchLabels:
      app: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          command: ["/bin/bash", "-c"]
          args:
            - |
              while [ ! -f /shared/ip.txt ]; do sleep 1; done
              TS_IP=$(cat /shared/ip.txt)
              
              echo "Using TS_IP: $TS_IP"
              sed -i "/^listen_address:/d" /etc/cassandra/cassandra.yaml
              sed -i "/^broadcast_address:/d" /etc/cassandra/cassandra.yaml
              sed -i "/^rpc_address:/d" /etc/cassandra/cassandra.yaml
              sed -i "/^broadcast_rpc_address:/d" /etc/cassandra/cassandra.yaml
              
              sed -i "s/seeds: \"127.0.0.1:7000\"/seeds: \"$CASSANDRA_SEEDS\"/g" /etc/cassandra/cassandra.yaml
              sed -i "s/auto_bootstrap: false/auto_bootstrap: true/g" /etc/cassandra/cassandra.yaml
              sed -i "s/cluster_name: .*/cluster_name: $CASSANDRA_CLUSTER_NAME/" /etc/cassandra/cassandra.yaml
              sed -i "s/endpoint_snitch: .*/endpoint_snitch: GossipingPropertyFileSnitch/" /etc/cassandra/cassandra.yaml
              sed -i "s/dc=.*/dc=$CASSANDRA_DC/" /etc/cassandra/cassandra-rackdc.properties

              echo "listen_address: $TS_IP" >> /etc/cassandra/cassandra.yaml
              echo "broadcast_address: $TS_IP" >> /etc/cassandra/cassandra.yaml
              echo "rpc_address: 0.0.0.0" >> /etc/cassandra/cassandra.yaml
              echo "broadcast_rpc_address: $TS_IP" >> /etc/cassandra/cassandra.yaml
              cassandra -R -f
          env:
            - name: CASSANDRA_SEEDS
              value: "100.107.92.27:7000,100.79.253.86:7000"
            - name: CASSANDRA_CLUSTER_NAME
              value: "MainCluster"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: shared-data
              mountPath: /shared
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
        - name: tailscale
          image: tailscale/tailscale:latest
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              tailscaled &
              tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname=$(hostname)
              tailscale ip --4 | head -n1 > /shared/ip.txt
              tail -f /dev/null
              sleep infinity
          env:
            - name: TAILSCALE_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
          volumeMounts:
            - name: shared-data
              mountPath: /shared
            - name: tailscale-data
              mountPath: /var/lib/tailscale
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 100.100.100.100
        searches:
          - tailnet.local
          - svc.cluster.local
      volumes:
        - name: shared-data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: tailscale-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
